USE DATABASE DB_DEV;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS RAW.ORDERS_EXAMPLE (
  ORDER_ID STRING,
  CUSTOMER_ID STRING,
  ORDER_DATE DATE,
  ORDER_STATUS STRING,
  TOTAL_AMOUNT NUMBER(12,2),
  LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
