USE DATABASE DB_DEV;

SELECT
  CURRENT_ACCOUNT() AS ACCOUNT_NAME,
  CURRENT_USER() AS DEPLOY_USER,
  CURRENT_ROLE() AS DEPLOY_ROLE,
  CURRENT_DATABASE() AS DATABASE_NAME,
  CURRENT_WAREHOUSE() AS WAREHOUSE_NAME;

SHOW SCHEMAS IN DATABASE DB_DEV;
